import { useMemo, useState } from 'react'
import { Icon, type IconName } from './Icons'
import TopBar from './TopBar'
import type { Space, SpaceItem, SpaceItemType, WeekDay } from '../lib/core'

const ICONS: { name: IconName; label: string }[] = [
  { name: 'dumbbell', label: 'Gym' }, { name: 'leaf', label: 'Diet' }, { name: 'book', label: 'Study' },
  { name: 'briefcase', label: 'Work' }, { name: 'bulb', label: 'Ideas' }, { name: 'note', label: 'Notes' },
  { name: 'goal', label: 'Goals' }, { name: 'calendar', label: 'Plans' },
]
const DAYS: { id: WeekDay; label: string }[] = [{ id: 1, label: 'M' }, { id: 2, label: 'T' }, { id: 3, label: 'W' }, { id: 4, label: 'T' }, { id: 5, label: 'F' }, { id: 6, label: 'S' }, { id: 0, label: 'S' }]
const id = () => crypto.randomUUID()
const now = () => Date.now()
const starter = (name: string, icon: IconName): Space => ({ id: id(), name, icon, description: '', sections: [{ id: id(), title: 'Getting started', items: [] }], createdAt: now(), updatedAt: now() })

function SpaceModal({ initial, onSave, onClose }: { initial?: Space; onSave: (name: string, icon: IconName, description: string) => void; onClose: () => void }) {
  const [name, setName] = useState(initial?.name ?? '')
  const [icon, setIcon] = useState<IconName>(initial?.icon ?? 'note')
  const [description, setDescription] = useState(initial?.description ?? '')
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true">
    <div className="card modal-panel glass w-full max-w-md rounded-3xl p-5 shadow-2xl">
      <div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-teal">{initial ? 'Edit space' : 'New space'}</p><h2 className="mt-1 text-xl font-semibold">Build your own system</h2></div><button className="tap rounded-full text-muted hover:text-ink" onClick={onClose} aria-label="Close"><Icon name="close" /></button></div>
      <label className="mb-4 block"><span className="mb-2 block text-xs font-medium text-muted">Name</span><input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Gym, Study, Ideas…" className="w-full rounded-xl border border-line bg-bg/60 px-3 py-2.5 text-ink outline-none focus:border-teal" /></label>
      <label className="mb-4 block"><span className="mb-2 block text-xs font-medium text-muted">Short description <span className="opacity-50">optional</span></span><input value={description} onChange={e => setDescription(e.target.value)} placeholder="What belongs here?" className="w-full rounded-xl border border-line bg-bg/60 px-3 py-2.5 text-ink outline-none focus:border-teal" /></label>
      <div className="mb-6"><span className="mb-2 block text-xs font-medium text-muted">Icon</span><div className="grid grid-cols-8 gap-2">{ICONS.map(x => <button key={x.name} type="button" title={x.label} onClick={() => setIcon(x.name)} className={`grid aspect-square place-items-center rounded-xl border transition ${icon === x.name ? 'border-teal bg-teal/10 text-teal' : 'border-line bg-white/[.025] text-muted hover:text-ink'}`}><Icon name={x.name} className="size-5" /></button>)}</div></div>
      <div className="flex justify-end gap-2"><button className="rounded-xl px-4 py-2 text-sm text-muted hover:text-ink" onClick={onClose}>Cancel</button><button disabled={!name.trim()} className="rounded-xl bg-teal px-4 py-2 text-sm font-semibold text-bg disabled:cursor-not-allowed disabled:opacity-40" onClick={() => onSave(name.trim(), icon, description.trim())}>{initial ? 'Save changes' : 'Create space'}</button></div>
    </div>
  </div>
}

function ItemEditor({ initial, onSave, onClose }: { initial?: SpaceItem; onSave: (item: SpaceItem) => void; onClose: () => void }) {
  const [type, setType] = useState<SpaceItemType>(initial?.type ?? 'checklist')
  const [title, setTitle] = useState(initial?.title ?? '')
  const [content, setContent] = useState(initial?.content ?? '')
  const [days, setDays] = useState<WeekDay[]>(initial?.days ?? [])
  const save = () => onSave({ id: initial?.id ?? id(), type, title: title.trim() || (type === 'note' ? 'Untitled note' : 'Untitled item'), content, done: initial?.done ?? false, days: days.length ? days : undefined, createdAt: initial?.createdAt ?? now(), updatedAt: now() })
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="card modal-panel glass w-full max-w-lg rounded-3xl p-5 shadow-2xl">
    <div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-teal">Add to space</p><h2 className="mt-1 text-xl font-semibold">Make it useful</h2></div><button className="tap rounded-full text-muted hover:text-ink" onClick={onClose} aria-label="Close"><Icon name="close" /></button></div>
    <div className="mb-4 grid grid-cols-3 rounded-xl border border-line bg-bg/40 p-1">{(['checklist','list','note'] as SpaceItemType[]).map(t => <button key={t} onClick={() => setType(t)} className={`rounded-lg px-2 py-2 text-xs font-medium capitalize ${type === t ? 'bg-white/10 text-ink' : 'text-muted'}`}>{t}</button>)}</div>
    <input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder={type === 'note' ? 'Note title' : 'Item title'} className="mb-3 w-full rounded-xl border border-line bg-bg/60 px-3 py-2.5 text-ink outline-none focus:border-teal" />
    <textarea value={content} onChange={e => setContent(e.target.value)} rows={type === 'note' ? 7 : 3} placeholder={type === 'checklist' ? 'Optional details' : type === 'list' ? 'One item per line' : 'Write your note…'} className="w-full resize-y rounded-xl border border-line bg-bg/60 px-3 py-2.5 text-sm text-ink outline-none focus:border-teal" />
    {type !== 'note' && <div className="mt-4"><span className="mb-2 block text-xs font-medium text-muted">Repeat on <span className="opacity-50">optional</span></span><div className="flex gap-1.5">{DAYS.map(d => <button key={d.id} onClick={() => setDays(v => v.includes(d.id) ? v.filter(x => x !== d.id) : [...v, d.id])} className={`grid size-9 place-items-center rounded-full border text-xs font-semibold ${days.includes(d.id) ? 'border-teal bg-teal/10 text-teal' : 'border-line text-muted'}`}>{d.label}</button>)}</div><p className="mt-2 text-[11px] text-muted">Leave empty for a flexible item. Choose days for repeating routines like Monday Gym.</p></div>}
    <div className="mt-6 flex justify-end gap-2"><button className="rounded-xl px-4 py-2 text-sm text-muted" onClick={onClose}>Cancel</button><button className="rounded-xl bg-teal px-4 py-2 text-sm font-semibold text-bg" onClick={save}>Save</button></div>
  </div></div>
}

export default function Spaces({ spaces, onChange }: { spaces: Space[]; onChange: (spaces: Space[]) => void }) {
  const [selectedId, setSelectedId] = useState(spaces[0]?.id ?? '')
  const [spaceModal, setSpaceModal] = useState<'new' | 'edit' | null>(spaces.length ? null : 'new')
  const [itemModal, setItemModal] = useState<{ sectionId: string; item?: SpaceItem } | null>(null)
  const [addingSection, setAddingSection] = useState(false)
  const [sectionName, setSectionName] = useState('')
  const selected = spaces.find(s => s.id === selectedId) ?? spaces[0]
  const touch = (s: Space): Space => ({ ...s, updatedAt: now() })
  const createSpace = (name: string, icon: IconName, description: string) => { const s = { ...starter(name, icon), description }; onChange([...spaces, s]); setSelectedId(s.id); setSpaceModal(null) }
  const updateSpace = (name: string, icon: IconName, description: string) => { if (!selected) return; onChange(spaces.map(s => s.id === selected.id ? touch({ ...s, name, icon, description }) : s)); setSpaceModal(null) }
  const deleteSpace = () => { if (!selected || !confirm(`Delete “${selected.name}” and everything inside it?`)) return; const next = spaces.filter(s => s.id !== selected.id); onChange(next); setSelectedId(next[0]?.id ?? ''); if (!next.length) setSpaceModal('new') }
  const addSection = () => { if (!selected || !sectionName.trim()) return; onChange(spaces.map(s => s.id === selected.id ? touch({ ...s, sections: [...s.sections, { id: id(), title: sectionName.trim(), items: [] }] }) : s)); setSectionName(''); setAddingSection(false) }
  const removeSection = (sectionId: string) => { if (!selected) return; onChange(spaces.map(s => s.id === selected.id ? touch({ ...s, sections: s.sections.filter(x => x.id !== sectionId) }) : s)) }
  const moveSection = (sectionId: string, dir: -1 | 1) => { if (!selected) return; onChange(spaces.map(s => { if (s.id !== selected.id) return s; const a = [...s.sections], i = a.findIndex(x => x.id === sectionId), j = i + dir; if (i < 0 || j < 0 || j >= a.length) return s; [a[i], a[j]] = [a[j], a[i]]; return touch({ ...s, sections: a }) })) }
  const saveItem = (sectionId: string, item: SpaceItem) => { if (!selected) return; onChange(spaces.map(s => s.id === selected.id ? touch({ ...s, sections: s.sections.map(sec => sec.id === sectionId ? { ...sec, items: sec.items.some(i => i.id === item.id) ? sec.items.map(i => i.id === item.id ? item : i) : [...sec.items, item] } : sec) }) : s)); setItemModal(null) }
  const removeItem = (sectionId: string, itemId: string) => { if (!selected) return; onChange(spaces.map(s => s.id === selected.id ? touch({ ...s, sections: s.sections.map(sec => sec.id === sectionId ? { ...sec, items: sec.items.filter(i => i.id !== itemId) } : sec) }) : s)) }
  const toggleItem = (sectionId: string, itemId: string) => { if (!selected) return; onChange(spaces.map(s => s.id === selected.id ? touch({ ...s, sections: s.sections.map(sec => sec.id === sectionId ? { ...sec, items: sec.items.map(i => i.id === itemId ? { ...i, done: !i.done, updatedAt: now() } : i) } : sec) }) : s)) }
  const stats = useMemo(() => { const items = selected?.sections.flatMap(s => s.items) ?? []; return { total: items.length, done: items.filter(i => i.done).length } }, [selected])

  return <div className="space-y-5">
    <TopBar name=""><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-teal">Personal systems</p><h1 className="text-3xl font-bold tracking-tight">Spaces</h1><p className="mt-1 max-w-xl text-sm text-muted">Build your own system — one place for the things that matter to you.</p></div><button onClick={() => setSpaceModal('new')} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-teal px-3.5 py-2.5 text-sm font-semibold text-bg shadow-lg shadow-teal/10"><Icon name="plus" className="size-4" /> New space</button></TopBar>
    {spaces.length === 0 ? <div className="card glass rounded-3xl p-10 text-center"><div className="mx-auto mb-4 grid size-14 place-items-center rounded-2xl bg-teal/10 text-teal"><Icon name="bulb" className="size-7" /></div><h2 className="text-xl font-semibold">Start with a space</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted">Create a focused place for your gym routine, diet, study plan, work system, ideas, or anything else you want to build.</p><button onClick={() => setSpaceModal('new')} className="mt-6 rounded-xl bg-teal px-5 py-2.5 text-sm font-semibold text-bg">Create your first space</button></div> : <>
      <div className="flex gap-2 overflow-x-auto pb-1">{spaces.map(s => <button key={s.id} onClick={() => setSelectedId(s.id)} className={`group flex shrink-0 items-center gap-2 rounded-2xl border px-3 py-2 text-left transition ${selected?.id === s.id ? 'border-teal/60 bg-teal/10 text-ink' : 'border-line bg-white/[.025] text-muted hover:text-ink'}`}><span className="grid size-8 place-items-center rounded-xl bg-white/[.06]"><Icon name={s.icon} className="size-4" /></span><span className="max-w-28 truncate text-sm font-medium">{s.name}</span></button>)}</div>
      {selected && <div className="space-y-4"><div className="glass card rounded-3xl p-5"><div className="flex flex-wrap items-start gap-4"><div className="grid size-12 place-items-center rounded-2xl bg-teal/10 text-teal"><Icon name={selected.icon} className="size-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">{selected.name}</h2><span className="rounded-full border border-line px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-muted">{stats.done}/{stats.total} done</span></div><p className="mt-1 text-sm text-muted">{selected.description || 'A space for your system, your way.'}</p></div><div className="flex gap-1"><button className="tap rounded-xl text-muted hover:bg-white/5 hover:text-ink" title="Edit space" onClick={() => setSpaceModal('edit')}><Icon name="edit" className="size-4" /></button><button className="tap rounded-xl text-muted hover:bg-white/5 hover:text-red-300" title="Delete space" onClick={deleteSpace}><Icon name="close" className="size-4" /></button></div></div></div>
        {selected.sections.map((section, si) => <section key={section.id} className="card glass rounded-3xl p-4 sm:p-5"><div className="mb-3 flex items-center gap-2"><div className="min-w-0 flex-1"><h3 className="font-semibold">{section.title}</h3><p className="text-[11px] text-muted">{section.items.length} {section.items.length === 1 ? 'item' : 'items'}</p></div><button disabled={si === 0} onClick={() => moveSection(section.id, -1)} className="tap rounded-lg text-muted disabled:opacity-20" title="Move section up"><span className="rotate-[-90deg]"><Icon name="chevron" className="size-4" /></span></button><button disabled={si === selected.sections.length - 1} onClick={() => moveSection(section.id, 1)} className="tap rounded-lg text-muted disabled:opacity-20" title="Move section down"><span className="rotate-90"><Icon name="chevron" className="size-4" /></span></button><button onClick={() => removeSection(section.id)} className="tap rounded-lg text-muted hover:text-red-300" title="Delete section"><Icon name="close" className="size-4" /></button></div>
          <div className="space-y-2">{section.items.map(item => <div key={item.id} className={`group rounded-2xl border border-line bg-white/[.02] p-3 transition hover:bg-white/[.035] ${item.done ? 'opacity-60' : ''}`}><div className="flex items-start gap-3">{item.type === 'checklist' ? <button onClick={() => toggleItem(section.id, item.id)} aria-label={item.done ? 'Mark incomplete' : 'Mark complete'} className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded-md border ${item.done ? 'border-teal bg-teal text-bg' : 'border-muted/50 text-transparent hover:border-teal'}`}><Icon name="check" className="size-3" /></button> : <span className="mt-1 grid size-5 shrink-0 place-items-center text-muted"><Icon name={item.type === 'note' ? 'note' : 'check'} className="size-4" /></span>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`text-sm font-medium ${item.done ? 'line-through' : ''}`}>{item.title}</p>{item.days?.length ? <span className="rounded-full bg-teal/10 px-2 py-0.5 text-[9px] font-semibold text-teal">{item.days.map(d => DAYS.find(x => x.id === d)?.label).join(' ')}</span> : null}</div>{item.content && <p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-muted">{item.content}</p>}</div><div className="flex opacity-100 sm:opacity-0 sm:group-hover:opacity-100"><button className="tap rounded-lg text-muted hover:text-ink" onClick={() => setItemModal({ sectionId: section.id, item })} title="Edit"><Icon name="edit" className="size-3.5" /></button><button className="tap rounded-lg text-muted hover:text-red-300" onClick={() => removeItem(section.id, item.id)} title="Delete"><Icon name="close" className="size-3.5" /></button></div></div></div>)}
            <button onClick={() => setItemModal({ sectionId: section.id })} className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-line py-3 text-xs font-medium text-muted transition hover:border-teal/40 hover:bg-teal/[.03] hover:text-teal"><Icon name="plus" className="size-4" /> Add item</button>
          </div></section>)}
        {addingSection ? <div className="glass rounded-2xl border border-teal/30 p-3"><div className="flex gap-2"><input autoFocus value={sectionName} onChange={e => setSectionName(e.target.value)} onKeyDown={e => e.key === 'Enter' && addSection()} placeholder="Section name" className="min-w-0 flex-1 rounded-xl border border-line bg-bg/50 px-3 py-2 text-sm outline-none focus:border-teal" /><button onClick={addSection} className="rounded-xl bg-teal px-3 text-sm font-semibold text-bg">Add</button><button onClick={() => setAddingSection(false)} className="rounded-xl px-3 text-sm text-muted">Cancel</button></div></div> : <button onClick={() => setAddingSection(true)} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-line py-4 text-sm font-medium text-muted hover:border-teal/40 hover:text-teal"><Icon name="plus" className="size-4" /> Add section</button>}
      </div>}
    </>}
    {spaceModal && <SpaceModal initial={spaceModal === 'edit' ? selected : undefined} onSave={spaceModal === 'edit' ? updateSpace : createSpace} onClose={() => setSpaceModal(null)} />}
    {itemModal && <ItemEditor initial={itemModal.item} onSave={item => saveItem(itemModal.sectionId, item)} onClose={() => setItemModal(null)} />}
  </div>
}
